name: camtech_assessment_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

# THE FIX IS HERE: This line is updated to be more compatible
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # ADDED PACKAGES FOR THE NEW SERVICES
  http: ^1.2.1
  shared_preferences: ^2.2.3
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/quizz-welcome-image.png
    - assets/data/questions.json